### ISSUE TITLE
question: Does this tap require OAuth?

### ISSUE THREAD

**Issue by anden-akkio** [sehnem/tap-shopify#7]
## Background

Most other taps specified on the Meltano Hub require a token obtained via OAuth. https://hub.meltano.com/extractors/tap-shopify/

## Question

Is this tap any different, or does this require going through the same OAuth process? OAuth represents a lot of technical complexity we'd like to circumvent if possible as we work on expanding ways to import data into our platform, so I'd be curious to hear. 

Thank you! Keep up the great work.

**Comment by sehnem** [comment]
If it will be used by your store you can create a private app to get the token, and it should work with all the taps.
Here are some good [docs](https://docs.hotglue.com/docs/connectors-shopify) about it.

This tap will be under heavy development in the next weeks, so it is possible that the things change in it. Also, let me know if you are missing some feature and I can take a look at it.

**Comment by anden-akkio** [comment]
Private apps no longer seem to exist https://shopify.dev/docs/apps/distribution

And I'm apprehensive about a custom app; the table on the above Shopify docs seems to indicate OAuth will also be used there. Will continue to investigate.

**Comment by sehnem** [comment]
But you are able to generate a token for your store, I know that because I have done it with my test account and have never set an oauth flow for it.
